name: Trigger

on:
  push:
    branches: [ master ]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: thoth-station/jupyter-notebooks

    - name: Update the submodules
      run: |
        git submodule update --init --recursive
        
    - name: Create Pull Request
      id: pull_request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'Automatic update'
        body: |-
          The update has been triggered by commit [#${{ github.sha }}][0] and run [${{ github.run_id }}][1]

          [0]: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          [1]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        branch: update/${{ github.sha }}
        labels: update, bot, s2i-minimal-notebook
        team-reviewers: owners, maintainers
    - name: Check outputs
      run: |
        echo "Pull Request created: ${{ steps.pull_request.outputs.pr_number }}"
